function mostrar(name) {
    if (name == "add") {
        $("#add").hide();
        $("#addd").show();
        $("#adddd").show();
        $("#add-0").show();
        $("#add00").hide();
        $("#add000").hide();
        $("#add-1").hide();
        $("#add11").hide();
        $("#add111").hide();
        $("#add-2").hide();
        $("#add22").hide();
        $("#add222").hide();
        $("#add-3").hide();
        $("#add33").hide();
        $("#add333").hide();
        $("#add-4").hide();
        $("#add44").hide();
        $("#add444").hide();
        $("#add-5").hide();
        $("#add55").hide();
        $("#add555").hide();
    }
    if (name == "add0") {
        $("#add").hide();
        $("#addd").show();
        $("#adddd").show();
        $("#add-0").hide();
        $("#add00").show();
        $("#add000").show();
        $("#add-1").show();
        $("#add11").hide();
        $("#add111").hide();
        $("#add-2").hide();
        $("#add22").hide();
        $("#add222").hide();
        $("#add-3").hide();
        $("#add33").hide();
        $("#add333").hide();
        $("#add-4").hide();
        $("#add44").hide();
        $("#add444").hide();
        $("#add-5").hide();
        $("#add55").hide();
        $("#add555").hide();
    }
    if (name == "add1") {
        $("#add").hide();
        $("#addd").show();
        $("#adddd").show();
        $("#add-0").hide();
        $("#add00").show();
        $("#add000").show();
        $("#add-1").hide();
        $("#add11").show();
        $("#add111").show();
        $("#add-2").show();
        $("#add22").hide();
        $("#add222").hide();
        $("#add-3").hide();
        $("#add33").hide();
        $("#add333").hide();
        $("#add-4").hide();
        $("#add44").hide();
        $("#add444").hide();
        $("#add-5").hide();
        $("#add55").hide();
        $("#add555").hide();
    }
    if (name == "add2") {
        $("#add").hide();
        $("#addd").show();
        $("#adddd").show();
        $("#add-0").hide();
        $("#add00").show();
        $("#add000").show();
        $("#add-1").hide();
        $("#add11").show();
        $("#add111").show();
        $("#add-2").hide();
        $("#add22").show();
        $("#add222").show();
        $("#add-3").show();
        $("#add33").hide();
        $("#add333").hide();
        $("#add-4").hide();
        $("#add44").hide();
        $("#add444").hide();
        $("#add-5").hide();
        $("#add55").hide();
        $("#add555").hide();
    }
    if (name == "add3") {
        $("#add").hide();
        $("#addd").show();
        $("#adddd").show();
        $("#add-0").hide();
        $("#add00").show();
        $("#add000").show();
        $("#add-1").hide();
        $("#add11").show();
        $("#add111").show();
        $("#add-2").hide();
        $("#add22").show();
        $("#add222").show();
        $("#add-3").hide();
        $("#add33").show();
        $("#add333").show();
        $("#add-4").show();
        $("#add44").hide();
        $("#add444").hide();
        $("#add-5").hide();
        $("#add55").hide();
        $("#add555").hide();
    }
    if (name == "add4") {
        $("#add").hide();
        $("#addd").show();
        $("#adddd").show();
        $("#add-0").hide();
        $("#add00").show();
        $("#add000").show();
        $("#add-1").hide();
        $("#add11").show();
        $("#add111").show();
        $("#add-2").hide();
        $("#add22").show();
        $("#add222").show();
        $("#add-3").hide();
        $("#add33").show();
        $("#add333").show();
        $("#add-4").hide();
        $("#add44").show();
        $("#add444").show();
        $("#add-5").show();
        $("#add55").hide();
        $("#add555").hide();
    }
    if (name == "add5") {
        $("#add").hide();
        $("#addd").show();
        $("#adddd").show();
        $("#add-0").hide();
        $("#add00").show();
        $("#add000").show();
        $("#add-1").hide();
        $("#add11").show();
        $("#add111").show();
        $("#add-2").hide();
        $("#add22").show();
        $("#add222").show();
        $("#add-3").hide();
        $("#add33").show();
        $("#add333").show();
        $("#add-4").hide();
        $("#add44").show();
        $("#add444").show();
        $("#add-5").hide();
        $("#add55").show();
        $("#add555").show();
    }
}

$(document).ready(function(){
    $("#flexSwitch").click(function(){
        if($("#flexSwitch").is(":checked")){
            $("#hr_nc0").show();
            $("#hr_nc1").show();
            $("#hr_nc2").show();
            $("#hr_nc3").show();
            $("#hr_nc4").show();
            $("#hr_nc5").show();
            $("#hr_nc6").show();
            $("#hr_nc7").show();
            $("#hr_nc8").show();
            $("#hr_nc9").show();
            $("#hr_nc10").show();
        } else {
            $("#hr_nc0").hide();
            $("#hr_nc1").hide();
            $("#hr_nc2").hide();
            $("#hr_nc3").hide();
            $("#hr_nc4").hide();
            $("#hr_nc5").hide();
            $("#hr_nc6").hide();
            $("#hr_nc7").hide();
            $("#hr_nc8").hide();
            $("#hr_nc9").hide();
            $("#hr_nc10").hide();
        }
    })
})